### ISSUE TITLE
Size of food

### ISSUE THREAD

**Issue by wolframteetz** [j0ll3/SlitherBot#1]
Do you know how to get the size of a food dot?
Would be a great addition...

Nice bot :)

Cheers

**Comment by j0ll3** [comment]
Next time, please add a descriptive title, thanks!

I do not currently have the knowledge how to get the size of the food dot, but I will look into this after the basic AI is finished.

**Comment by j0ll3** [comment]
If someone is interested, here is a sample object of a food blob:

```
Object
cv: 5
cv2: 4
eaten_fr: 0
fh: 45
fh2: 22.5
fr: 1
fw: 45
fw2: 22.5
g2cv: 14
g2fh: 141
g2fh2: 70.5
g2fw: 141
g2fw2: 70.5
gcv: 7
gfh: 85
gfh2: 42.5
gfr: 771.4274924916016
gfw: 85
gfw2: 42.5
gr: 1.17
id: 1348050819
lrrad: 1
ofh: 15
ofh2: 7.5
ofw: 15
ofw2: 7.5
rad: 1
rsp: 2
rx: 16424.269647255445
ry: 20800.13105981185
sx: 54
sy: 69
sz: 5.2
wsp: -0.0006462755589745938
xx: 16419
yy: 20803
```

I know that keys that begin g* and g2* are connected to canvas (and drawing).

**Comment by wolframteetz** [comment]
Thanks for the code. No problem. I forked your project and modified it for myself. I also fixed some bugs, you might want to take a look at it. Check <240 for the transmitted byte, otherwise you will get unwanted acceleration. Also, check the math.abs() for the direction, it only goes lower right corner with your code.

**Comment by j0ll3** [comment]
I think the new version has this corrected (distance is now calculated with sqrt and I updated the direction function). In case you find bugs (and have a fix for them), you can always make a push request. I'll look into that link later.

**Comment by j0ll3** [comment]
I have found that the key `gr` contains the size of the food. (In the example object it is `gr: 1.17`)

Going to implement this soon.
